// Topic-aware boss configuration — every visual, dialogue, and mechanic derives from this.
export const BOSS_CONFIG = {
  variables: {
    name: 'Memory Titan',
    subtitle: 'Guardian of the Variable Vault',
    arena: 'vault',
    primaryColor: '#3b82f6',
    secondaryColor: '#1d4ed8',
    glowColor: 'rgba(59, 130, 246, 0.7)',
    particleColor: '#93c5fd',
    bgFrom: '#020617', bgMid: '#0f172a', bgTo: '#030712',
    abilities: ['Memory Corruption', 'Variable Overwrite', 'Stack Collapse'],
    dialogue: {
      english: {
        intro: '"So... you believe you understand memory?"',
        phase2: '"My registers overflow with your failures."',
        phase3: '"I will corrupt every variable you hold!"',
        playerWinning: '"You learn quickly... not quick enough."',
        playerLosing: '"Your stack is collapsing..."',
        comboBreak: '"Your sequence... broken."',
        bigCombo: '"Impossible. Recalculating..."',
        victory: '"The Vault has been breached. Impressive."',
        defeat: '"Your variables... undefined."',
      },
      hindi: {
        intro: '"Kya tu sach mein memory samajh gaya?"',
        phase2: '"Mere registers teri galtiyon se bhare hain."',
        phase3: '"Main teri har variable corrupt kar dunga!"',
        playerWinning: '"Seekh raha hai jaldi... kafi nahi."',
        playerLosing: '"Tera stack collapse ho raha hai..."',
        comboBreak: '"Tera sequence... toot gaya."',
        bigCombo: '"Impossible. Recalculating..."',
        victory: '"Vault breach ho gaya. Zabardast."',
        defeat: '"Teri variables... undefined hain."',
      },
      tamil: {
        intro: '"நீ memory புரிந்துகொண்டதாக நம்புகிறாயா?"',
        phase2: '"என் registers உன் தோல்விகளால் நிரம்பியுள்ளன."',
        phase3: '"உனது எல்லா variables-ஐயும் நான் corrupt செய்வேன்!"',
        playerWinning: '"விரைவாக கற்கிறாய்... ஆனால் போதவில்லை."',
        playerLosing: '"உன் stack இடிந்து விழுகிறது..."',
        comboBreak: '"உன் sequence... உடைந்தது."',
        bigCombo: '"Impossible. மீண்டும் கணக்கிடுகிறேன்..."',
        victory: '"Vault உடைக்கப்பட்டது. ஈர்க்கிறது."',
        defeat: '"உன் variables... undefined ஆகிவிட்டன."',
      },
      malayalam: {
        intro: '"നിനക്ക് memory മനസ്സിലായി എന്ന് വിശ്വസിക്കുന്നോ?"',
        phase2: '"എന്റെ registers നിന്റെ തോൽവികൾ കൊണ്ട് നിറഞ്ഞിരിക്കുന്നു."',
        phase3: '"നിന്റെ ഓരോ variable-ഉം ഞാൻ corrupt ചെയ്യും!"',
        playerWinning: '"പെട്ടെന്ന് പഠിക്കുന്നു... പക്ഷേ പോരാ."',
        playerLosing: '"നിന്റെ stack തകർന്നു വീഴുകയാണ്..."',
        comboBreak: '"നിന്റെ sequence... broken."',
        bigCombo: '"Impossible. വീണ്ടും കണക്കാക്കുന്നു..."',
        victory: '"Vault breach ചെയ്തു. ഗംഭീരം."',
        defeat: '"നിന്റെ variables... undefined ആയി."',
      },
    },
  },

  'data-types': {
    name: 'The Shape Shifter',
    subtitle: 'Architect of the Digital Forge',
    arena: 'forge',
    primaryColor: '#f59e0b',
    secondaryColor: '#d97706',
    glowColor: 'rgba(245, 158, 11, 0.7)',
    particleColor: '#fcd34d',
    bgFrom: '#0c0a00', bgMid: '#1c1400', bgTo: '#0a0800',
    abilities: ['Type Mutation', 'Conversion Beam', 'Boolean Collapse'],
    dialogue: {
      english: {
        intro: '"Every type... is mine to mutate."',
        phase2: '"You cannot contain my transformation!"',
        phase3: '"BOOLEAN OVERLOAD. ALL TYPES COLLAPSE."',
        playerWinning: '"You read types well... for now."',
        playerLosing: '"Your type system... is breaking."',
        comboBreak: '"Ha. Type error detected."',
        bigCombo: '"Conversion successful? Impossible."',
        victory: '"The Forge bends to no student."',
        defeat: '"All values... converted to zero."',
      },
      hindi: {
        intro: '"Har type... mera hai mutate karne ke liye."',
        phase2: '"Tu meri transformation rok nahi sakta!"',
        phase3: '"BOOLEAN OVERLOAD. SAB TYPES COLLAPSE."',
        playerWinning: '"Types ache se padh leta hai... abhi ke liye."',
        playerLosing: '"Tera type system... toot raha hai."',
        comboBreak: '"Ha. Type error pakad liya."',
        bigCombo: '"Conversion hua? Impossible."',
        victory: '"Forge kisi student ke aage nahi jhukta."',
        defeat: '"Sab values... zero mein convert ho gayi."',
      },
      tamil: {
        intro: '"ஒவ்வொரு type-ம்... என்னால் மாற்றப்படும்."',
        phase2: '"என் மாற்றத்தை நீ தடுக்க முடியாது!"',
        phase3: '"BOOLEAN OVERLOAD. அனைத்து TYPES COLLAPSE."',
        playerWinning: '"Types நன்றாக படிக்கிறாய்... இப்போதைக்கு."',
        playerLosing: '"உன் type system... உடைகிறது."',
        comboBreak: '"ஹா. Type error கண்டறிந்தேன்."',
        bigCombo: '"Conversion வெற்றியா? Impossible."',
        victory: '"Forge எந்த student-க்கும் முன்பு குனியாது."',
        defeat: '"அனைத்து values... zero ஆகிவிட்டன."',
      },
      malayalam: {
        intro: '"ഓരോ type-ഉം... എന്റേതാണ് mutate ചെയ്യാൻ."',
        phase2: '"എന്റെ transformation നിനക്ക് തടയാനാകില്ല!"',
        phase3: '"BOOLEAN OVERLOAD. എല്ലാ TYPES COLLAPSE."',
        playerWinning: '"Types നന്നായി വായിക്കുന്നു... ഇപ്പോഴത്തേക്ക്."',
        playerLosing: '"നിന്റെ type system... തകരുന്നു."',
        comboBreak: '"ഹ. Type error detected."',
        bigCombo: '"Conversion ശരിയോ? Impossible."',
        victory: '"Forge ഒരു student-ന് മുന്നിലും കുനിയില്ല."',
        defeat: '"എല്ലാ values... zero ആയി."',
      },
    },
  },

  conditions: {
    name: 'The Branch Warden',
    subtitle: 'Keeper of Every Path',
    arena: 'labyrinth',
    primaryColor: '#10b981',
    secondaryColor: '#059669',
    glowColor: 'rgba(16, 185, 129, 0.7)',
    particleColor: '#6ee7b7',
    bgFrom: '#001a0d', bgMid: '#002915', bgTo: '#000f08',
    abilities: ['False Path', 'Condition Lock', 'Infinite Branch'],
    dialogue: {
      english: {
        intro: '"Every choice you make... I control."',
        phase2: '"Your branching logic fails me."',
        phase3: '"ALL PATHS LEAD TO DEFEAT."',
        playerWinning: '"Smart choices. Suspicious."',
        playerLosing: '"Your else clause is empty..."',
        comboBreak: '"Wrong branch. Penalty applied."',
        bigCombo: '"That condition... should have been False."',
        victory: '"The Labyrinth opens for you."',
        defeat: '"Condition: False. Game over."',
      },
      hindi: {
        intro: '"Tu jo bhi choice kare... main control karta hoon."',
        phase2: '"Teri branching logic fail ho gayi."',
        phase3: '"SAB PATHS DEFEAT MEIN JAATE HAIN."',
        playerWinning: '"Sahi choices. Suspicious hai."',
        playerLosing: '"Tera else clause khali hai..."',
        comboBreak: '"Galat branch. Penalty laga di."',
        bigCombo: '"Wo condition... False honi chahiye thi."',
        victory: '"Labyrinth teri wajah se khula."',
        defeat: '"Condition: False. Game over."',
      },
      tamil: {
        intro: '"நீ எந்த தேர்வு செய்தாலும்... நான் control செய்கிறேன்."',
        phase2: '"உன் branching logic தோல்வியடைந்தது."',
        phase3: '"அனைத்து PATHS-உம் தோல்விக்கு வழிவகுக்கின்றன."',
        playerWinning: '"சரியான தேர்வுகள். சந்தேகமாக இருக்கிறது."',
        playerLosing: '"உன் else clause காலியாக உள்ளது..."',
        comboBreak: '"தவறான branch. Penalty விதிக்கப்பட்டது."',
        bigCombo: '"அந்த condition... False ஆக இருந்திருக்க வேண்டும்."',
        victory: '"Labyrinth உனக்காக திறக்கிறது."',
        defeat: '"Condition: False. Game over."',
      },
      malayalam: {
        intro: '"നീ ഏത് തിരഞ്ഞെടുപ്പ് ചെയ്താലും... ഞാൻ control ചെയ്യുന്നു."',
        phase2: '"നിന്റെ branching logic fail ആയി."',
        phase3: '"എല്ലാ PATHS-ഉം defeat-ലേക്ക് നയിക്കുന്നു."',
        playerWinning: '"ശരിയായ choices. സംശയകരം."',
        playerLosing: '"നിന്റെ else clause empty ആണ്..."',
        comboBreak: '"തെറ്റായ branch. Penalty ഇട്ടു."',
        bigCombo: '"ആ condition... False ആയിരിക്കണ്ടതായിരുന്നു."',
        victory: '"Labyrinth നിനക്കായി തുറക്കുന്നു."',
        defeat: '"Condition: False. Game over."',
      },
    },
  },

  loops: {
    name: 'Infinite Hydra',
    subtitle: 'Sovereign of the Endless Time Chamber',
    arena: 'timechamber',
    primaryColor: '#8b5cf6',
    secondaryColor: '#7c3aed',
    glowColor: 'rgba(139, 92, 246, 0.8)',
    particleColor: '#c4b5fd',
    bgFrom: '#0d0020', bgMid: '#1a0035', bgTo: '#05001a',
    abilities: ['Infinite Spin', 'Recursive Strike', 'Endless Summons'],
    dialogue: {
      english: {
        intro: '"Escape my infinite cycle... if you can."',
        phase2: '"The loop never ends. Neither do I."',
        phase3: '"RECURSION OVERFLOW. EVERYTHING REPEATS."',
        playerWinning: '"Your iteration is... precise."',
        playerLosing: '"You are stuck. Forever iterating."',
        comboBreak: '"Loop broken. Reset initiated."',
        bigCombo: '"Your break statement found me? Clever."',
        victory: '"The cycle... has finally terminated."',
        defeat: '"While True: you lose. Forever."',
      },
      hindi: {
        intro: '"Mere infinite cycle se nikal... agar kar sake to."',
        phase2: '"Loop kabhi nahi rukta. Main bhi nahi."',
        phase3: '"RECURSION OVERFLOW. SAB DOBARA HOGA."',
        playerWinning: '"Teri iteration... bilkul sahi hai."',
        playerLosing: '"Tu fas gaya. Hamesha iterate karta rahega."',
        comboBreak: '"Loop toot gaya. Reset shuru."',
        bigCombo: '"Tera break statement ne mujhe dhundh liya? Chalak."',
        victory: '"Cycle... aakhirkar terminate ho gayi."',
        defeat: '"While True: tu haara. Hamesha."',
      },
      tamil: {
        intro: '"என் infinite cycle-இலிருந்து தப்பி... முடியுமா பார்!"',
        phase2: '"Loop ஒருபோதும் முடியாது. நானும் முடியமாட்டேன்."',
        phase3: '"RECURSION OVERFLOW. எல்லாமே மீண்டும் நடக்கும்."',
        playerWinning: '"உன் iteration... துல்லியமாக உள்ளது."',
        playerLosing: '"நீ சிக்கிவிட்டாய். என்றும் iterate செய்துகொண்டே இருப்பாய்."',
        comboBreak: '"Loop உடைந்தது. Reset தொடங்கியது."',
        bigCombo: '"உன் break statement என்னை கண்டுபிடித்ததா? புத்திசாலி."',
        victory: '"Cycle... இறுதியாக terminate ஆனது."',
        defeat: '"While True: நீ தோற்றாய். என்றென்றும்."',
      },
      malayalam: {
        intro: '"എന്റെ infinite cycle-ൽ നിന്ന് രക്ഷപ്പെടൂ... കഴിയുമെങ്കിൽ."',
        phase2: '"Loop ഒരിക്കലും അവസാനിക്കില്ല. ഞാനും."',
        phase3: '"RECURSION OVERFLOW. എല്ലാം ആവർത്തിക്കും."',
        playerWinning: '"നിന്റെ iteration... precise ആണ്."',
        playerLosing: '"നീ കുടുങ്ങി. എന്നും iterate ചെയ്തുകൊണ്ടിരിക്കും."',
        comboBreak: '"Loop broken. Reset ആരംഭിച്ചു."',
        bigCombo: '"നിന്റെ break statement എന്നെ കണ്ടുപിടിച്ചോ? ബുദ്ധിമാൻ."',
        victory: '"Cycle... ഒടുവിൽ terminate ആയി."',
        defeat: '"While True: നീ തോറ്റു. എന്നും."',
      },
    },
  },

  functions: {
    name: 'The Function Architect',
    subtitle: 'Master of the Ancient Arcane Library',
    arena: 'library',
    primaryColor: '#ec4899',
    secondaryColor: '#db2777',
    glowColor: 'rgba(236, 72, 153, 0.7)',
    particleColor: '#f9a8d4',
    bgFrom: '#1a0010', bgMid: '#2d0020', bgTo: '#0d0008',
    abilities: ['Recursive Clone', 'Return Blast', 'Parameter Storm'],
    dialogue: {
      english: {
        intro: '"Every call has consequences."',
        phase2: '"My recursion has no base case for you."',
        phase3: '"STACK OVERFLOW. ALL RETURNS VOID."',
        playerWinning: '"Clean function. No side effects. Noted."',
        playerLosing: '"Your parameters... are wrong."',
        comboBreak: '"Return value: None."',
        bigCombo: '"That... was a perfect function call."',
        victory: '"Function complete. Return: Victory."',
        defeat: '"Your call stack... has overflowed."',
      },
      hindi: {
        intro: '"Har call ka natija hota hai."',
        phase2: '"Meri recursion ka tere liye koi base case nahi."',
        phase3: '"STACK OVERFLOW. SAB RETURNS VOID."',
        playerWinning: '"Clean function. Koi side effect nahi. Note kar liya."',
        playerLosing: '"Tere parameters... galat hain."',
        comboBreak: '"Return value: None."',
        bigCombo: '"Woh... ek perfect function call tha."',
        victory: '"Function complete. Return: Jeet."',
        defeat: '"Tera call stack... overflow ho gaya."',
      },
      tamil: {
        intro: '"ஒவ்வொரு call-க்கும் விளைவுகள் உண்டு."',
        phase2: '"என் recursion-க்கு உனக்கான base case இல்லை."',
        phase3: '"STACK OVERFLOW. அனைத்து RETURNS VOID."',
        playerWinning: '"சுத்தமான function. Side effects இல்லை. கவனித்தேன்."',
        playerLosing: '"உன் parameters... தவறானவை."',
        comboBreak: '"Return value: None."',
        bigCombo: '"அது... ஒரு perfect function call ஆக இருந்தது."',
        victory: '"Function முடிந்தது. Return: வெற்றி."',
        defeat: '"உன் call stack... overflow ஆனது."',
      },
      malayalam: {
        intro: '"ഓരോ call-നും consequences ഉണ്ട്."',
        phase2: '"എന്റെ recursion-ന് നിനക്ക് base case ഇല്ല."',
        phase3: '"STACK OVERFLOW. എല്ലാ RETURNS VOID."',
        playerWinning: '"Clean function. Side effects ഇല്ല. Note ചെയ്തു."',
        playerLosing: '"നിന്റെ parameters... തെറ്റാണ്."',
        comboBreak: '"Return value: None."',
        bigCombo: '"അത്... ഒരു perfect function call ആയിരുന്നു."',
        victory: '"Function complete. Return: വിജയം."',
        defeat: '"നിന്റെ call stack... overflow ആയി."',
      },
    },
  },

  lists: {
    name: 'List Leviathan',
    subtitle: 'Beast of the Floating Ocean of Data',
    arena: 'ocean',
    primaryColor: '#06b6d4',
    secondaryColor: '#0891b2',
    glowColor: 'rgba(6, 182, 212, 0.7)',
    particleColor: '#67e8f9',
    bgFrom: '#000d12', bgMid: '#001520', bgTo: '#00080d',
    abilities: ['Slice Attack', 'Append Swarm', 'Index Crash'],
    dialogue: {
      english: {
        intro: '"I contain multitudes. You contain... none."',
        phase2: '"My index is out of your bounds."',
        phase3: '"LIST MUTATION. ALL INDICES CORRUPTED."',
        playerWinning: '"Correct slice. My length shortens."',
        playerLosing: '"IndexError: student out of range."',
        comboBreak: '"Your list... just got popped."',
        bigCombo: '"list.append(respect)... Reluctantly."',
        victory: '"The Ocean of Data yields to you."',
        defeat: '"Your list... is empty now."',
      },
      hindi: {
        intro: '"Main bahut kuch rakhta hoon. Tu... kuch bhi nahi."',
        phase2: '"Mera index teri boundary se bahar hai."',
        phase3: '"LIST MUTATION. SAB INDICES CORRUPT."',
        playerWinning: '"Sahi slice. Meri length kam ho rahi hai."',
        playerLosing: '"IndexError: student out of range."',
        comboBreak: '"Teri list... abhi pop ho gayi."',
        bigCombo: '"list.append(izzat)... Majbooran."',
        victory: '"Data ka Ocean tere aage jhuk gaya."',
        defeat: '"Teri list... ab khali hai."',
      },
      tamil: {
        intro: '"நான் அனைத்தையும் கொண்டுள்ளேன். நீ... ஒன்றும் இல்லை."',
        phase2: '"என் index உன் boundary-க்கு வெளியே உள்ளது."',
        phase3: '"LIST MUTATION. அனைத்து INDICES CORRUPT."',
        playerWinning: '"சரியான slice. என் length குறைகிறது."',
        playerLosing: '"IndexError: student out of range."',
        comboBreak: '"உன் list... இப்போது pop ஆனது."',
        bigCombo: '"list.append(மரியாதை)... தயக்கத்துடன்."',
        victory: '"Data Ocean உனக்கு வழிவிடுகிறது."',
        defeat: '"உன் list... இப்போது காலியாகிவிட்டது."',
      },
      malayalam: {
        intro: '"ഞാൻ ബഹുത്വം ഉൾക്കൊള്ളുന്നു. നിനക്ക്... ഒന്നുമില്ല."',
        phase2: '"എന്റെ index നിന്റെ bounds-ന് പുറത്താണ്."',
        phase3: '"LIST MUTATION. എല്ലാ INDICES CORRUPT."',
        playerWinning: '"ശരിയായ slice. എന്റെ length കുറയുന്നു."',
        playerLosing: '"IndexError: student out of range."',
        comboBreak: '"നിന്റെ list... pop ആയി."',
        bigCombo: '"list.append(ബഹുമാനം)... വൈക്ലഭ്യത്തോടെ."',
        victory: '"Data-ന്റെ Ocean നിനക്ക് വഴിമാറി."',
        defeat: '"നിന്റെ list... ഇപ്പോൾ empty ആണ്."',
      },
    },
  },

  strings: {
    name: 'Cipher Phantom',
    subtitle: 'Ghost of the Neon Code Cathedral',
    arena: 'cathedral',
    primaryColor: '#a855f7',
    secondaryColor: '#9333ea',
    glowColor: 'rgba(168, 85, 247, 0.8)',
    particleColor: '#d8b4fe',
    bgFrom: '#0d001a', bgMid: '#1a0030', bgTo: '#050010',
    abilities: ['Split Beam', 'Reverse Slash', 'Replace Wave'],
    dialogue: {
      english: {
        intro: '"I am every string. I am none."',
        phase2: '"Your pattern matching... is weak."',
        phase3: '"CIPHER MODE. ALL TEXT REVERSED."',
        playerWinning: '"Correct format. I am... impressed."',
        playerLosing: '"ValueError: invalid literal."',
        comboBreak: '"String terminated prematurely."',
        bigCombo: '"f-string mastery detected. Noted."',
        victory: '"The Cathedral decodes for you."',
        defeat: '"Your string... has no escape character."',
      },
      hindi: {
        intro: '"Main har string hoon. Main kuch bhi nahi hoon."',
        phase2: '"Tera pattern matching... kamzor hai."',
        phase3: '"CIPHER MODE. SAB TEXT ULTA."',
        playerWinning: '"Sahi format. Main... impress hua."',
        playerLosing: '"ValueError: invalid literal."',
        comboBreak: '"String jaldi khatam ho gayi."',
        bigCombo: '"f-string mastery pakdi. Note kar liya."',
        victory: '"Cathedral ne tere liye decode kar diya."',
        defeat: '"Teri string... mein koi escape character nahi."',
      },
      tamil: {
        intro: '"நான் ஒவ்வொரு string-ம். நான் எதுவும் இல்லை."',
        phase2: '"உன் pattern matching... பலவீனமாக உள்ளது."',
        phase3: '"CIPHER MODE. அனைத்து TEXT-ம் தலைகீழாகிவிட்டது."',
        playerWinning: '"சரியான format. நான்... impressed."',
        playerLosing: '"ValueError: invalid literal."',
        comboBreak: '"String முன்கூட்டியே முடிந்தது."',
        bigCombo: '"f-string mastery கண்டறியப்பட்டது. கவனித்தேன்."',
        victory: '"Cathedral உனக்காக decode செய்கிறது."',
        defeat: '"உன் string... escape character இல்லை."',
      },
      malayalam: {
        intro: '"ഞാൻ ഓരോ string-ഉം ആണ്. ഞാൻ ഒന്നുമല്ല."',
        phase2: '"നിന്റെ pattern matching... ദുർബലമാണ്."',
        phase3: '"CIPHER MODE. എല്ലാ TEXT-ഉം reversed."',
        playerWinning: '"ശരിയായ format. ഞാൻ... impressed."',
        playerLosing: '"ValueError: invalid literal."',
        comboBreak: '"String നേരത്തേ terminate ആയി."',
        bigCombo: '"f-string mastery കണ്ടെത്തി. Note ചെയ്തു."',
        victory: '"Cathedral നിനക്കായി decode ചെയ്തു."',
        defeat: '"നിന്റെ string-ന്... escape character ഇല്ല."',
      },
    },
  },

  oop: {
    name: 'Class Emperor',
    subtitle: 'Ruler of the Cyber Kingdom',
    arena: 'kingdom',
    primaryColor: '#f97316',
    secondaryColor: '#ea580c',
    glowColor: 'rgba(249, 115, 22, 0.7)',
    particleColor: '#fdba74',
    bgFrom: '#150500', bgMid: '#200800', bgTo: '#0a0200',
    abilities: ['Inheritance Strike', 'Encapsulation Shield', 'Polymorph Attack'],
    dialogue: {
      english: {
        intro: '"I am the base class of all power."',
        phase2: '"My subclasses are endless. You are not."',
        phase3: '"POLYMORPHISM ACTIVATED. ALL FORMS UNLEASHED."',
        playerWinning: '"You understand my hierarchy. Dangerous."',
        playerLosing: '"AttributeError: no class detected."',
        comboBreak: '"__del__ initiated on your progress."',
        bigCombo: '"Method resolution order: you... then me."',
        victory: '"The Kingdom recognizes your OOP mastery."',
        defeat: '"TypeError: not an instance of winner."',
      },
      hindi: {
        intro: '"Main sab shakti ka base class hoon."',
        phase2: '"Mere subclasses anant hain. Tu nahi."',
        phase3: '"POLYMORPHISM ACTIVATE. SAB FORMS UNLEASHED."',
        playerWinning: '"Tu meri hierarchy samajhta hai. Khatarnak."',
        playerLosing: '"AttributeError: koi class nahi mila."',
        comboBreak: '"__del__ teri progress par shuru hua."',
        bigCombo: '"Method resolution order: pehle tu... phir main."',
        victory: '"Kingdom ne teri OOP mastery maan li."',
        defeat: '"TypeError: winner ka instance nahi."',
      },
      tamil: {
        intro: '"நான் அனைத்து சக்திகளின் base class."',
        phase2: '"என் subclasses எண்ணற்றவை. நீ இல்லை."',
        phase3: '"POLYMORPHISM ACTIVATE. அனைத்து FORMS UNLEASHED."',
        playerWinning: '"என் hierarchy புரிந்துகொண்டாய். ஆபத்தானது."',
        playerLosing: '"AttributeError: class கண்டறியப்படவில்லை."',
        comboBreak: '"__del__ உன் progress-ல் தொடங்கியது."',
        bigCombo: '"Method resolution order: முதல் நீ... பிறகு நான்."',
        victory: '"Kingdom உன் OOP mastery-ஐ அங்கீகரிக்கிறது."',
        defeat: '"TypeError: winner-இன் instance இல்லை."',
      },
      malayalam: {
        intro: '"ഞാൻ എല്ലാ ശക്തിയുടെയും base class ആണ്."',
        phase2: '"എന്റെ subclasses അനന്തമാണ്. നീ അല്ല."',
        phase3: '"POLYMORPHISM ACTIVATE. എല്ലാ FORMS UNLEASHED."',
        playerWinning: '"എന്റെ hierarchy മനസ്സിലായി. അപകടകരം."',
        playerLosing: '"AttributeError: class കണ്ടെത്തിയില്ല."',
        comboBreak: '"__del__ നിന്റെ progress-ൽ ആരംഭിച്ചു."',
        bigCombo: '"Method resolution order: ആദ്യം നീ... പിന്നെ ഞാൻ."',
        victory: '"Kingdom നിന്റെ OOP mastery അംഗീകരിച്ചു."',
        defeat: '"TypeError: winner-ന്റെ instance അല്ല."',
      },
    },
  },

  'error-handling': {
    name: 'Corruption Core',
    subtitle: 'Sovereign of the Broken Server Realm',
    arena: 'brokenserver',
    primaryColor: '#ef4444',
    secondaryColor: '#dc2626',
    glowColor: 'rgba(239, 68, 68, 0.8)',
    particleColor: '#fca5a5',
    bgFrom: '#1a0000', bgMid: '#2d0000', bgTo: '#0d0000',
    abilities: ['Exception Storm', 'Crash Pulse', 'Stack Trace Beam'],
    dialogue: {
      english: {
        intro: '"Every program breaks. Especially yours."',
        phase2: '"Unhandled exception detected: you."',
        phase3: '"CRITICAL ERROR. CORE DUMPED."',
        playerWinning: '"try/except written correctly? Unexpected."',
        playerLosing: '"Traceback: fatal error in your logic."',
        comboBreak: '"RuntimeError: combo not defined."',
        bigCombo: '"Your error handling... is actually valid."',
        victory: '"System restored. Corruption defeated."',
        defeat: '"Process terminated. Exit code: 1."',
      },
      hindi: {
        intro: '"Har program toot ta hai. Tere wala toh zaroor."',
        phase2: '"Unhandled exception detect hua: tu."',
        phase3: '"CRITICAL ERROR. CORE DUMP HO GAYA."',
        playerWinning: '"try/except sahi likha? Unexpected."',
        playerLosing: '"Traceback: teri logic mein fatal error."',
        comboBreak: '"RuntimeError: combo define nahi."',
        bigCombo: '"Teri error handling... actually valid hai."',
        victory: '"System restore hua. Corruption defeat."',
        defeat: '"Process terminate hua. Exit code: 1."',
      },
      tamil: {
        intro: '"ஒவ்வொரு program-ம் உடையும். உன்னுடையது கண்டிப்பாக."',
        phase2: '"Unhandled exception கண்டறியப்பட்டது: நீ."',
        phase3: '"CRITICAL ERROR. CORE DUMP ஆனது."',
        playerWinning: '"try/except சரியாக எழுதினாயா? எதிர்பார்க்கவில்லை."',
        playerLosing: '"Traceback: உன் logic-ல் fatal error."',
        comboBreak: '"RuntimeError: combo define இல்லை."',
        bigCombo: '"உன் error handling... உண்மையிலேயே valid."',
        victory: '"System restore ஆனது. Corruption தோற்றது."',
        defeat: '"Process terminate ஆனது. Exit code: 1."',
      },
      malayalam: {
        intro: '"ഓരോ program-ഉം ഉടയുന്നു. നിന്റേത് കൂടുതൽ."',
        phase2: '"Unhandled exception detected: നീ."',
        phase3: '"CRITICAL ERROR. CORE DUMP ആയി."',
        playerWinning: '"try/except ശരിയായി എഴുതിയോ? Unexpected."',
        playerLosing: '"Traceback: നിന്റെ logic-ൽ fatal error."',
        comboBreak: '"RuntimeError: combo define ചെയ്തിട്ടില്ല."',
        bigCombo: '"നിന്റെ error handling... യഥാർഥത്തിൽ valid."',
        victory: '"System restore ആയി. Corruption defeated."',
        defeat: '"Process terminated. Exit code: 1."',
      },
    },
  },

  algorithms: {
    name: 'Algorithm Overlord',
    subtitle: 'Master of the Quantum Computation Nexus',
    arena: 'nexus',
    primaryColor: '#14b8a6',
    secondaryColor: '#0d9488',
    glowColor: 'rgba(20, 184, 166, 0.7)',
    particleColor: '#5eead4',
    bgFrom: '#000d0c', bgMid: '#001a18', bgTo: '#00080a',
    abilities: ['Binary Storm', 'Search Beam', 'Sorting Vortex'],
    dialogue: {
      english: {
        intro: '"Efficiency determines survival."',
        phase2: '"O(n²)? Your approach is... inefficient."',
        phase3: '"QUANTUM SORT INITIATED. RESISTANCE IS O(1)."',
        playerWinning: '"Optimal solution found. Unexpected."',
        playerLosing: '"Time complexity: infinite for you."',
        comboBreak: '"Search failed. Key not found."',
        bigCombo: '"O(log n) precision. I acknowledge this."',
        victory: '"Algorithm solved. Nexus yields."',
        defeat: '"Stack overflow. Memory limit exceeded."',
      },
      hindi: {
        intro: '"Efficiency hi survival decide karti hai."',
        phase2: '"O(n²)? Tera approach... inefficient hai."',
        phase3: '"QUANTUM SORT SHURU. RESISTANCE IS O(1)."',
        playerWinning: '"Optimal solution mila. Unexpected."',
        playerLosing: '"Time complexity: tere liye infinite."',
        comboBreak: '"Search fail hua. Key nahi mili."',
        bigCombo: '"O(log n) precision. Main manta hoon."',
        victory: '"Algorithm solve hua. Nexus haara."',
        defeat: '"Stack overflow. Memory limit par gaya."',
      },
      tamil: {
        intro: '"Efficiency மட்டுமே survival-ஐ தீர்மானிக்கிறது."',
        phase2: '"O(n²)? உன் approach... inefficient."',
        phase3: '"QUANTUM SORT தொடங்கியது. RESISTANCE IS O(1)."',
        playerWinning: '"Optimal solution கண்டறியப்பட்டது. எதிர்பார்க்கவில்லை."',
        playerLosing: '"Time complexity: உனக்கு infinite."',
        comboBreak: '"Search தோல்வியடைந்தது. Key கிடைக்கவில்லை."',
        bigCombo: '"O(log n) precision. இதை ஏற்றுக்கொள்கிறேன்."',
        victory: '"Algorithm solve ஆனது. Nexus தோற்றது."',
        defeat: '"Stack overflow. Memory limit தாண்டியது."',
      },
      malayalam: {
        intro: '"Efficiency മാത്രമേ survival നിർണ്ണയിക്കുന്നുള്ളൂ."',
        phase2: '"O(n²)? നിന്റെ approach... inefficient."',
        phase3: '"QUANTUM SORT ആരംഭിച്ചു. RESISTANCE IS O(1)."',
        playerWinning: '"Optimal solution കണ്ടെത്തി. Unexpected."',
        playerLosing: '"Time complexity: നിനക്ക് infinite."',
        comboBreak: '"Search fail ആയി. Key കണ്ടെത്തിയില്ല."',
        bigCombo: '"O(log n) precision. ഞാൻ ഇത് അംഗീകരിക്കുന്നു."',
        victory: '"Algorithm solved. Nexus yield ആയി."',
        defeat: '"Stack overflow. Memory limit exceeded."',
      },
    },
  },
}

export const getBossConfig = (topicId) =>
  BOSS_CONFIG[topicId] || BOSS_CONFIG.variables

// Get boss dialogue in the player's language (falls back to English)
export const getBossDialogue = (topicId, language, key) => {
  const config = getBossConfig(topicId)
  const lang = ['english', 'hindi', 'tamil', 'malayalam'].includes(language) ? language : 'english'
  return config.dialogue[lang]?.[key] || config.dialogue.english[key] || ''
}
