const BADGES = [
  {
    id: 'first_step',
    name: 'First Step',
    nameHindi: 'पहला कदम',
    emoji: '🌱',
    description: 'Complete your first topic',
    descriptionHindi: 'पहला topic complete करो',
  },
  {
    id: 'on_fire',
    name: 'On Fire',
    nameHindi: 'आग लगा दी',
    emoji: '🔥',
    description: 'Complete 3 topics',
    descriptionHindi: '3 topics complete करो',
  },
  {
    id: 'stem_master',
    name: 'STEM Master',
    nameHindi: 'STEM मास्टर',
    emoji: '🧠',
    description: 'Complete all 10 topics',
    descriptionHindi: 'सभी 10 topics complete करो',
  },
  {
    id: 'speed_demon',
    name: 'Speed Demon',
    nameHindi: 'स्पीड डेमन',
    emoji: '⚡',
    description: 'Complete 5 topics in Speed Mode',
    descriptionHindi: 'Speed Mode में 5 topics complete करो',
  },
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    nameHindi: 'वीक वॉरियर',
    emoji: '📅',
    description: 'Maintain a 7-day streak',
    descriptionHindi: '7 दिन की streak रखो',
  },
  {
    id: 'consistent',
    name: 'Consistent',
    nameHindi: 'कंसिस्टेंट',
    emoji: '💪',
    description: 'Maintain a 14-day streak',
    descriptionHindi: '14 दिन की streak रखो',
  },
  {
    id: 'unstoppable',
    name: 'Unstoppable',
    nameHindi: 'अनस्टॉपेबल',
    emoji: '👑',
    description: 'Maintain a 30-day streak',
    descriptionHindi: '30 दिन की streak रखो',
  },
  {
    id: 'sharpshooter',
    name: 'Sharpshooter',
    nameHindi: 'शार्पशूटर',
    emoji: '🎯',
    description: '10 consecutive correct answers',
    descriptionHindi: '10 लगातार सही जवाब',
  },
  {
    id: 'level_up',
    name: 'Level Up',
    nameHindi: 'लेवल अप',
    emoji: '🚀',
    description: 'Reach Level 5 in any topic',
    descriptionHindi: 'किसी भी topic में Level 5 तक पहुंचो',
  },
  {
    id: 'perfectionist',
    name: 'Perfectionist',
    nameHindi: 'परफेक्शनिस्ट',
    emoji: '💯',
    description: '100% accuracy in any topic level',
    descriptionHindi: 'किसी level में 100% accuracy',
  },
  {
    id: 'ai_slayer',
    name: 'AI Slayer',
    nameHindi: 'AI स्लेयर',
    emoji: '⚔️',
    description: 'Complete your first AI Challenge',
    descriptionHindi: 'पहला AI Challenge complete करो',
  },
  {
    id: 'challenge_champion',
    name: 'Challenge Champion',
    nameHindi: 'चैलेंज चैंपियन',
    emoji: '🏆',
    description: 'Complete all AI Challenges',
    descriptionHindi: 'सभी AI Challenges complete करो',
  },
]

module.exports = BADGES
